name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e68c0eb193ee58dce8b8b85335cea01d09cf8bf4a12bbb0960afda4b8420850b"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
