name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bd980254649502ca5e351c47b9239b8dd4f14557d47c30c37a4408a36cb865c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
