name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a62485b06fa6497b8ae995345503fac65c10a62fed724268392abca2765c942"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
