name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68101f42d223f0fb4c3fa3cac459e0cab820012ebe0d927895c6b43b0e39fe13"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
