name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a51c89a294b5e1e1ee0785fa162028cb42bc54d9b7e975d1f1690c3dde452be1"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
