name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eee78fdc2cc347948cc527e8b86273bb99f0f4b5e1801c20bee66f2caf69974"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
