name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fc68add61d59dcea1961ec37fda4b82791049f383d4c14dd4a6b52dfe65e464"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
