name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7bff28ca595c98e83b8c6eadbd6681840181186db57d37d7b709db6e79db15c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
