name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "021cd2eceeee0bad2f9884e6572bc7699da65fd17c9e697b9f855044214847d1"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
