name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0f4afb2e4a626514a96e8524237bb509865bbeac6029b9b931fd8d08340e0ae"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
