name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2553de1480060b3118c4be1ed9c54b73713a7f023ba7207b4bdbc6ac152e863"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
