name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b94c806a20fb5f450f21ac7212421b6301b98495e8ca8d243cb088f74b0abe3"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
