name = "springmp24"
author = "otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db6f363b648680e4899efea458ee154c0a59ed36e8ed5a42978826bdfebb3759"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"

[options]
datapack-folder = "global_packs/required_data"
